const {app:_0x1A,BrowserWindow:_0x2B,ipcMain:_0x3C,dialog:_0x4D}=require('electron'),_0x5E=require('path'),_0x6F=require('fs'),{exiftool:_0x7G}=require('exiftool-vendored');
let _0x8H;const _0x9I=()=>Buffer.from('VEhUIEV4aWYgVGVtaXpsZXlpY2k=','base64').toString('utf-8');
function _0x0J(){_0x8H=new _0x2B({width:800,height:600,backgroundColor:'#0d0d0d',title:_0x9I(),webPreferences:{preload:_0x5E.join(__dirname,'preload.js'),contextIsolation:!0,nodeIntegration:!1}});_0x8H.setMenuBarVisibility(!1);_0x8H.loadFile('index.html');}
_0x1A.whenReady().then(_0x0J);
_0x3C.handle('select-file',async()=>{const _0xA1=await _0x4D.showOpenDialog(_0x8H,{properties:['openFile'],title:Buffer.from('xLDFn2xlbSBpw6dpbiBkb3N5YSBzZcOnaW4=','base64').toString('utf-8')});return _0xA1.canceled?null:_0xA1.filePaths[0];});
const _0xB2=_0xC3=>{const _0xD4=`${_0xC3}_original`;_0x6F.existsSync(_0xD4)&&_0x6F.unlinkSync(_0xD4);};
_0x3C.handle('clean-metadata',async(_0xE5,_0xF6)=>{try{await _0x7G.deleteAllTags(_0xF6);_0xB2(_0xF6);return{success:!0,message:Buffer.from('RGF0YSBUZW1pemxlbmRp','base64').toString('utf-8')};}catch(_0xG7){return{success:!1,message:_0xG7.message};}});
_0x3C.handle('randomize-metadata',async(_0H8,_0xI9)=>{try{await _0x7G.deleteAllTags(_0xI9);const _0xJ0=()=>Math.random().toString(36).substring(2,10),_0xK1=()=>Math.floor(Math.random()*31)+1980,_0xL2=()=>String(Math.floor(Math.random()*12)+1).padStart(2,'0'),_0xM3=()=>String(Math.floor(Math.random()*28)+1).padStart(2,'0'),_0xN4=`${_0xK1()}:${_0xL2()}:${_0xM3()} 12:00:00`;const _0xO5={Make:Buffer.from('R2hvc3RfTWFudWZhY3R1cmVy','base64').toString('utf-8'),Model:`Unknown_Device_${_0xJ0()}`,Software:`THT_Sec_Wiper_v${Math.floor(Math.random()*10)}.0`,CreatorTool:'THT_Framework',Artist:'THT_Anonymous',Author:'THT_Agent',Creator:'THT',Producer:'THT_Engine',Copyright:'Classified - THT',Title:`Op_${_0xJ0()}`,Subject:'Nullified',Description:'Erased.',CreateDate:_0xN4,ModifyDate:_0xN4,DateTimeOriginal:_0xN4,GPSLatitude:0,GPSLatitudeRef:'N',GPSLongitude:0,GPSLongitudeRef:'E',GPSAltitude:0,DocumentID:`xmp.did:${_0xJ0()}-${_0xJ0()}`,InstanceID:`xmp.iid:${_0xJ0()}-${_0xJ0()}`};await _0x7G.write(_0xI9,_0xO5);_0xB2(_0xI9);return{success:!0,message:Buffer.from('RG9zeWEgdGVtaXpsZW5kaSB2ZSBzYWh0ZSBUSFQgdmVyaWxlcml5bGUgemVoaXJsZW5kaSE=','base64').toString('utf-8')};}catch(_0xP6){return{success:!1,message:_0xP6.message};}});
_0x1A.on('before-quit',()=>_0x7G.end());_0x1A.on('window-all-closed',()=>{process.platform!=='darwin'&&_0x1A.quit();});
